# Copyright (c) 2018 Kent R. Spillner <kspillner@acm.org>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

FROM ${REPOSITORY}/aur-pkgbuild-base:${ARCH_VERSION}

ENV ARCH_VERSION ${ARCH_VERSION}

ENV IRSSI_SIGNING_KEY ${IRSSI_SIGNING_KEY}

ENV VERSION ${VERSION}

ENV REFRESHED_AT ${DATE}

# Ensure elinks(1) is installed
RUN [ "/usr/bin/pacman", "--noconfirm", "--sync", "--quiet", "elinks" ]

# Populate irssi-icb sources
COPY --chown=_build:_build irssi-icb/ /opt/irssi-icb/

# Download irssi source & GPG signature
ADD --chown=_build:_build https://github.com/irssi/irssi/releases/download/${VERSION}/irssi-${VERSION}.tar.xz /opt/
ADD --chown=_build:_build https://github.com/irssi/irssi/releases/download/${VERSION}/irssi-${VERSION}.tar.xz.asc /opt/

# Create & chown irssi source directory
RUN [ "/usr/sbin/mkdir", "/opt/irssi-${VERSION}" ]
RUN [ "/usr/sbin/chown", "_build:_build", "/opt/irssi-${VERSION}" ]

USER _build
WORKDIR /opt

# Extract the official irssi signing key & show its fingerprint
RUN [ "/usr/sbin/gpg", "--homedir=/opt/irssi-${VERSION}/.gnupg", "--recv-keys", "${IRSSI_SIGNING_KEY}" ]
RUN [ "/usr/sbin/gpg", "--homedir=/opt/irssi-${VERSION}/.gnupg", "--fingerprint", "staff@irssi.org" ]

# Verify the release distribution
RUN [ "/usr/sbin/gpg", "--homedir=/opt/irssi-${VERSION}/.gnupg", "--verify", "/opt/irssi-${VERSION}.tar.xz.asc" ]

# Configure & build irssi
RUN [ "/usr/bin/tar", "xf", "/opt/irssi-${VERSION}.tar.xz" ]
WORKDIR /opt/irssi-${VERSION}
RUN [ "/opt/irssi-${VERSION}/configure", "--prefix=/usr", "--sysconfdir=/etc", "--with-proxy", "--with-perl-lib=vendor" ]
RUN [ "/usr/bin/make" ]

# Configure & build irssi-icb
WORKDIR /opt/irssi-icb
RUN [ "/opt/irssi-icb/autorun.sh" ]
RUN [ "/usr/sbin/mkdir", "/opt/irssi-icb/build" ]
WORKDIR /opt/irssi-icb/build
RUN [ "/opt/irssi-icb/configure", "--prefix=/opt/output", "--with-irssi=/opt/irssi-${VERSION}" ]
RUN [ "/usr/bin/make" ]

# Install the plugin
CMD [ "/usr/bin/make", "install" ]
